version: "3.7"
services:
  proyecto-microservice:
    container_name: proyecto-microservice
    image: proyecto-microservice:v1
    build: 
      context: .
    ports: 
      - "4001:4001"
    networks:
      - proyectos-app


networks: 
  proyectos-app: